version = 0.1
[default.deploy.parameters]
stack_name = "kafka-devnexus-producer"
resolve_s3 = true
s3_prefix = "kafka-devnexus-producer"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
